// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// SECDED decoder generated by util/design/secded_gen.py

module el2_secded_13_8_dec (
  input        [12:0] data_i,
  output logic [7:0] data_o,
  output logic [4:0] syndrome_o,
  output logic [1:0] err_o
);

  always_comb begin : p_encode
    // Syndrome calculation
    syndrome_o[0] = ^(data_i & 13'h01EA);
    syndrome_o[1] = ^(data_i & 13'h0297);
    syndrome_o[2] = ^(data_i & 13'h0473);
    syndrome_o[3] = ^(data_i & 13'h08AD);
    syndrome_o[4] = ^(data_i & 13'h105C);

    // Corrected output calculation
    data_o[0] = (syndrome_o == 5'he) ^ data_i[0];
    data_o[1] = (syndrome_o == 5'h7) ^ data_i[1];
    data_o[2] = (syndrome_o == 5'h1a) ^ data_i[2];
    data_o[3] = (syndrome_o == 5'h19) ^ data_i[3];
    data_o[4] = (syndrome_o == 5'h16) ^ data_i[4];
    data_o[5] = (syndrome_o == 5'hd) ^ data_i[5];
    data_o[6] = (syndrome_o == 5'h15) ^ data_i[6];
    data_o[7] = (syndrome_o == 5'hb) ^ data_i[7];

    // err_o calc. bit0: single error, bit1: double error
    err_o[0] = ^syndrome_o;
    err_o[1] = ~err_o[0] & (|syndrome_o);
  end
endmodule : el2_secded_13_8_dec
