// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// SECDED encoder generated by util/design/secded_gen.py

module el2_secded_13_8_enc (
  input        [7:0] data_i,
  output logic [12:0] data_o
);

  always_comb begin : p_encode
    data_o = 13'(data_i);
    data_o[8] = ^(data_o & 13'h00EA);
    data_o[9] = ^(data_o & 13'h0097);
    data_o[10] = ^(data_o & 13'h0073);
    data_o[11] = ^(data_o & 13'h00AD);
    data_o[12] = ^(data_o & 13'h005C);
  end

endmodule : el2_secded_13_8_enc
