name: Spike Build

on:
  workflow_call:

jobs:
  verilator:
    name: Build Spike
    runs-on: ubuntu-latest
    env:
      TOOL_NAME: spike
      TOOL_VERSION: d70ea67d
      DEBIAN_FRONTEND: "noninteractive"

    steps:
      - name: Setup Cache Metadata
        id: cache_metadata
        run: |
          cache_date=$(date +"%Y_%m_%d")
          cache_name=cache_${{ env.TOOL_NAME }}_${{ env.TOOL_VERSION }}
          echo "Cache date: "$cache_date
          echo "Cache name: "$cache_name
          echo "cache_date=$cache_date" >> "$GITHUB_ENV"
          echo "cache_name=$cache_name" >> "$GITHUB_ENV"

      - name: Setup cache
        uses: actions/cache@v3
        id: cache
        timeout-minutes: 60
        with:
          path: |
            /opt/spike
            /opt/spike/.cache
          key: ${{ env.cache_name }}_${{ env.cache_date }}
          restore-keys: ${{ env.cache_name }}_

      - name: Install prerequisities
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        run: |
          sudo apt -qqy update && sudo apt -qqy --no-install-recommends install \
            git build-essential cmake ccache device-tree-compiler

      - name: Build Spike
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        run: |
          export CCACHE_DIR=/opt/spike/.cache
          ccache --show-config | grep cache_dir
          git clone https://github.com/riscv-software-src/riscv-isa-sim spike
          export CC="ccache gcc"
          export CXX="ccache g++"
          pushd spike
            git checkout ${{ env.TOOL_VERSION }}

            # FIXME: these replaces should be done in a VeeR-specific Spike fork
            #
            # Rationale: VeeR pulls down bits 31 and 30 of pmpaddrn CSRs to 0.
            # This change is required so that we don't get mismatches related
            # to read/write operations on PMP CSRs:
            #
            #   Mismatch[1]:
            #   ISS[23] : pc[80000068] csrrw   a1, pmpaddr0, a1: a1:f75f83f1 c944_pmpaddr0:2000044f
            #   HDL[23] : pc[80000068] : a1:375f83f1 c3b0:2000044f
            sed -i 's/((reg_t(1) << (MAX_PADDR_BITS - PMP_SHIFT)) - 1);/0x3fffffff;/g' riscv/csrs.cc
            sed -i 's/return (addr >> MAX_PADDR_BITS) == 0;/return (addr >> 32) == 0;/g' riscv/sim.cc

            mkdir build
            cd build
            ../configure --prefix=/opt/spike
            make -j`nproc`
            make install
          popd
          rm -rf /opt/spike/include # Remove include and lib to save space
          rm -rf /opt/spike/lib

