name: verible-format-this

on:
  push:
    branches:
      - 'main'

jobs:
  verible-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: chipsalliance/verible-formatter-action/trigger-receive@main
    - uses: chipsalliance/verible-formatter-action@main
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        fail_on_formatting_suggestions: ${{ github.event_name != 'pull_request' }}
